#include <QtCore/QCoreApplication>
#include <iostream>
#include <windows.h>
#include <atlbase.h>
#include <wmp.h>
#include <tlhelp32.h>
#include "Movement.h"
#include "Player.h"
#include "Enemy.h"
#define STB_IMAGE_IMPLEMENTATION
#include <stb/stb_image.h>
#include <QApplication>
#include <QMainWindow>
#include <QIcon>
#include <QtOpenGL>
#include <QLabel>
#include <QUiLoader>
#include <QFile>
#include "qcheckbox.h"
#include "qstyle.h"
#include "qpushbutton.h"
#include "qboxlayout.h"
#include <algorithm>
#include <iostream>
#include <string>
#include <thread>
#include <vector>
#pragma once
