#include <QtCore/QCoreApplication>
#include <iostream>
#include <windows.h>
#include <atlbase.h>
#include <wmp.h>
#include <tlhelp32.h>
#include "Movement.h"
#include "Enemy.h"
#include <QApplication>
#include <QMainWindow>
#include <QIcon>
#include <QtOpenGL>
#include <QLabel>
#include <QUiLoader>
#include <QFile>
#include "qcheckbox.h"
#include "qstyle.h"
#include "qpushbutton.h"
#include "qboxlayout.h"
#include "qopengl.h"
#include "qopenglwidget.h"
#include <algorithm>
#include <iostream>
#include <string>
#include <thread>
#include <vector>
#include "qtimer.h"
#pragma once
